(load "employees.scm")
(perform "employees.dat")
;(perform "employees.dat" "count")
;(perform "employees.dat" "total")
;(perform "employees.dat" "avg")
;(perform "employees.dat" "min")
;(perform "employees.dat" "max")
;(perform "employees.dat" "max" "lt" 1800)
;(perform "employees.dat" "print" "ge" 2000)
(perform "employees2.dat" "print")