(load "employees.scm")
(perform "DATA4")
(perform "DATA99" "print")
(perform "DATA1" "print")
(perform "DATA2" "print")
(perform "DATA3" "print")
(perform "DATA4" "print" "eq" 170)
(perform "DATA4" "count" "ne" 5000)
(perform "DATA4" "max" "lt" 1900)
(perform "DATA4" "min" "gt" 1900)
(perform "DATA4" "total" "ge" 700)
(perform "DATA4" "avg" "le" 5000)