OBJECTS = main.cpp salariedEmployee.cpp hourlyEmployee.cpp comissionEmployee.cpp Employee.cpp reading.cpp
EXEC = a.out
FLAGS = -Wall
$(EXEC): $(OBJECTS)
	g++ $(FLAGS) -std=c++11 $(OBJECTS) -o $(EXEC)

clean:
	rm -f $(EXEC)


